# Ansible
# ansible_user: root

# Kubernetes
kube_version: v1.20.4
token: b0f7b8.8d1767876297d85c

# 1.8.x feature: --feature-gates SelfHosting=true
init_opts: ""

# Any other additional opts you want to add..
kubeadm_opts: ""
# For example:
# kubeadm_opts: '--apiserver-cert-extra-sans "k8s.domain.com,kubernetes.domain.com"'

service_cidr: "10.96.0.0/12"

pod_network_cidr: "10.244.0.0/16"
#network_cidr:
#      flannel: "10.244.0.0/16"
#      calico: "192.168.0.0/16"

#pod_network_cidr: "{{ network_cidr[network] }}"

# Supported Network implementation('flannel', 'calico')
network: calico

# Change this to an appropriate interface, preferably a private network.
# For example, on DigitalOcean, you would use eth1 as that is the default private network interface.
network_interface: ""

enable_dashboard: yes
need_to_save_dashboard_token: yes

# A list of insecure registries you might need to define
# insecure_registries: []
insecure_registries: ['gcr.io']

systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon

# Additional feature to install
additional_features:
  helm: false
  nfs_dynamic: true
  metric_server: true

# temporary directory used by additional features
tmp_dir: /opt/k8s


#Supported container_runtime: [ docker containerd crio]
container_runtime: crio

#for setting admin.conf 
k8s_config:
    path: /root
    user: root
    group: root

#nfs dir    
nfs:
  dir: /nfs-private
