---
- name: "Create checkout directory"
  file:
    path: 
      - "{{ kube_addon_dir }}"
      - "{{ kube_addon_dir }}/elk"
    state: directory
    mode: 0755

- name: "Copy Logging ELK files to {{ kube_addon_dir }}/elk folder"
  copy:
   src: kubernetes-elk/ 
   dest: "{{ kube_addon_dir }}/elk/"
   mode: 0755
   remote_src: no

- name: Deploying ELK
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} apply -f {{ kube_addon_dir }}/elk/"
  run_once: true
  retries: 5
  delay: 3

- debug:
     msg: "Kibana Dashboard available on http://{{ groups['worker'][0] }}:31336"

