---
- name: Deleting Master node
  block:
    - name: Getting Masternode Instance ID
      shell: AWS_ACCESS_KEY_ID="{{ access_key }}" AWS_SECRET_ACCESS_KEY="{{ secret_key }}" aws ec2 describe-instances --region={{ ec2.region }} --filter 'Name=tag:Name,Values={{ ec2.master.vm_tag }}' | grep InstanceId | cut -d':' -f2 | sed "s/\"//g" | sed s/'\s'//g | sed "s/\,//g" 
      register: masternode
      ignore_errors: true

    - name: Deleting MasterNode
      shell: AWS_ACCESS_KEY_ID="{{ access_key }}" AWS_SECRET_ACCESS_KEY="{{ secret_key }}" aws ec2 terminate-instances --region={{ ec2.region }} --instance-ids="{{ item }}"
      with_items:
            - "{{ masternode.stdout_lines }}"
      ignore_errors: true

- name: Deleting Worker node
  block:
    - name: Getting Workernode Instance ID
      shell: AWS_ACCESS_KEY_ID="{{ access_key }}" AWS_SECRET_ACCESS_KEY="{{ secret_key }}" aws ec2 describe-instances --region={{ ec2.region }} --filter 'Name=tag:Name,Values={{ ec2.worker.vm_tag }}' | grep InstanceId | cut -d':' -f2 | sed "s/\"//g" | sed s/'\s'//g | sed "s/\,//g"
      register: workernode
      ignore_errors: true

    - name: Deleting WorkerNode
      shell: AWS_ACCESS_KEY_ID="{{ access_key }}" AWS_SECRET_ACCESS_KEY="{{ secret_key }}" aws ec2 terminate-instances --region={{ ec2.region }} --instance-ids="{{ item }}"
      with_items:
        - "{{ workernode.stdout_lines }}"
      ignore_errors: true
