---
- name: Getting AWS cli 
  block:
    - name: Getting AWS CLI  binary file
      get_url:
          url: "{{ ec2.aws_cli.cli_url }}" 
          dest: "{{ ec2.temp_dir }}/awscli.zip"
          force_basic_auth: yes

    - name: Unzipping it
      unarchive:
           src: "{{ ec2.temp_dir }}/awscli.zip"
           dest: "{{ ec2.temp_dir }}"
           remote_src: yes

- name: Deleting Master node
  block:
    - name: Getting Masternode Instance ID
      shell: AWS_ACCESS_KEY_ID="{{ access_key }}" AWS_SECRET_ACCESS_KEY="{{ secret_key }}" "{{ ec2.temp_dir }}"/aws/dist/aws ec2 describe-instances --region={{ ec2.region }} --filter 'Name=tag:Name,Values={{ ec2.master.vm_tag }}' | grep InstanceId | cut -d':' -f2 | sed "s/\"//g" | sed s/'\s'//g | sed "s/\,//g" 
      register: masternode
      ignore_errors: true

    - name: Deleting MasterNode
      shell: AWS_ACCESS_KEY_ID="{{ access_key }}" AWS_SECRET_ACCESS_KEY="{{ secret_key }}" "{{ ec2.temp_dir }}"/aws/dist/aws ec2 terminate-instances --region={{ ec2.region }} --instance-ids="{{ item }}"
      with_items:
            -  "{{ masternode.stdout_lines }}"
      ignore_errors: true

- name: Deleting Worker node
  block:
    - name: Getting Workernode Instance ID
      shell: AWS_ACCESS_KEY_ID="{{ access_key }}" AWS_SECRET_ACCESS_KEY="{{ secret_key }}" "{{ ec2.temp_dir }}"/aws/dist/aws ec2 describe-instances --region={{ ec2.region }} --filter 'Name=tag:Name,Values={{ ec2.worker.vm_tag }}' | grep InstanceId | cut -d':' -f2 | sed "s/\"//g" | sed s/'\s'//g | sed "s/\,//g"
      register: workernode
      ignore_errors: true

    - name: Deleting WorkerNode
      shell: AWS_ACCESS_KEY_ID="{{ access_key }}" AWS_SECRET_ACCESS_KEY="{{ secret_key }}" "{{ ec2.temp_dir }}"/aws/dist/aws ec2 terminate-instances --region={{ ec2.region }} --instance-ids="{{ item }}"
      with_items:
        -  "{{ workernode.stdout_lines }}"
      ignore_errors: true
