---
- name: "[CNI] Create Kubernetes Network Directory"
  file:
     path: "{{ network_dir }}"
     state: directory
     mode: '0644'

- name: "[CNI] Downloading {{ network }} YAML files"
  template:
       src: "{{ network }}.yml.j2"
       dest: "{{ network_dir }}/{{ network }}.yml"
       mode: '0644'

- block:
   - name: "[CNI] Check {{ network }} daemonset is working"
     shell: kubectl --kubeconfig={{ kubeadmin_config }} get ds --all-namespaces | grep {{ network }}
     delegate_to: "{{ groups['master'][0] }}"
     run_once: true
     register: check_net
     no_log: true
     changed_when: false
  rescue:
   - name: "[CNI] Deploy {{ network }} Network daemonset"
     when: check_net is failed
     command: kubectl apply --kubeconfig={{ kubeadmin_config }} -f {{ network_dir }}/
     delegate_to: "{{ groups['master'][0] }}"
     run_once: true
