---
- name: "Create checkout directory"
  file:
    path: "{{ kube_addon_dir }}/metric-server"
    state: directory
    mode: 0755

- name: "Copy Metric Server setup file"
  copy:
   src: metric-server/
   dest: "{{ kube_addon_dir }}/metric-server/"
   mode: 0755
   remote_src: no

- name: Deploying Metric Server
  shell: "kubectl --kubeconfig={{ kubeadmin_config }} apply -f {{ kube_addon_dir }}/metric-server/"
  run_once: true
  retries: 10
  delay: 2
