language: python
os: linux
sudo: required
services:
  - docker
python:
  - "3.6"
before_install:
  - pip install -U ansible
script:
  - ansible-playbook -i testing-local.ini .cluster.yml -vvv --syntax-check
