---
- hosts: localhost
  roles:
    - { role: infra }

- hosts: master
  gather_facts: false
  become: yes
  roles:
    - { role: k8s/master }
    - { role: cni }

- hosts: worker
  gather_facts: false
  become: yes
  roles:
    - { role: k8s/worker }

- hosts: master
  gather_facts: false
  become: yes
  tasks:
    - name: "Helm role"
      include_role:
            name: k8s-addon/helm
      when: additional_features.helm | bool
      run_once: yes 

    - name: "Dashboard"
      include_role:
           name: k8s-addon/dashboard
      when: enable_dashboard | bool
      run_once: yes
