---
- hosts: localhost
  roles:
    - { role: infra }

- hosts: master
  gather_facts: false
  become: yes
  roles:
    - { role: k8s/master }
    - { role: cni }

- hosts: worker
  gather_facts: false
  become: yes
  roles:
    - { role: k8s/worker }

