---
- hosts: master
  gather_facts: false
  become: yes
  tasks:
    - name: "Dashboard"
      include_role:
           name: k8s-addon/dashboard
      when: enable_dashboard | bool
      run_once: yes
