apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: {{ .Values.storage_class_name }}
provisioner: {{ .Values.provisioner }}
reclaimPolicy: {{ .Values.reclaimPolicy }}
volumeBindingMode: {{ .Values.volumeBindingMode }} 
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"
