---
- name: Launching Master Node
  ec2:
    key_name: "{{ ec2.aws_key.name }}"
    instance_type: "{{ ec2.master.vm_type }}"
    image: "{{ ec2.vm_image[ec2.region] }}"
    wait: "{{ ec2.master.need_to_wait }}"
    group: "{{ ec2.security_group.group_name }}"
    count: "{{ ec2.master.vm_count }}"
    vpc_subnet_id: "{{ vpc_subid }}"
    assign_public_ip: "{{ ec2.master.need_public_ip }}"
    termination_protection: "{{ ec2.master.vm_protection }}"
    region: "{{ ec2.region }}"
    user_data: |
               #!/bin/bash
               apt update -y
               apt install curl python-y
               curl https://raw.githubusercontent.com/khann-adill/play-with-kubectl/master/kubernetes-installation/set-hostname-kmaster.sh | bash
    state: "{{ ec2.master.vm_state }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    volumes:
        - device_name: "{{ ec2.master.volume.volume_device_name }}"
          volume_type: "{{ ec2.master.volume.volume_type }}"
          volume_size: "{{ ec2.master.volume.volume_size }}"
          delete_on_termination: "{{ ec2.master.volume.volume_termination }}"
    instance_tags:
          Name: "{{ ec2.master.vm_tag }}"
  register: master_info

- name: "Setting MasterNode Public IP as variable"
  set_fact:
      master_ip: "{{ item.public_ip }}"
  loop: "{{ master_info['instances'] }}"
  
- name: Getting Inventory file.
  template:
     src: custom_inv.j2
     dest: "{{ inventory.inv_location }}/{{ inventory.inv_name }}"

- name: Adding MasterNode to inventory file.
  lineinfile:
        line: "{{ item.public_ip }} ansible_ssh_private_key_file={{ ec2.ssh_key.key_path }}/{{ ec2.ssh_key.key_name }} "
        dest: "{{ inventory.inv_location }}/{{ inventory.inv_name }}"
        insertafter: '\[master\]'
  loop: "{{ master_info['instances'] }}"
