---
- name: Checking PIP Installed or not
  shell: python3 -m pip --version
  register: pip
  ignore_errors: true
  changed_when: False

- name: Installing PIP
  apt:
    name: python3-pip
    state: present
  when: 
    - "'No' in pip.stderr"
    - ansible_os_family == "Debian"

- name: Installing AWS module dependency BOTO and BOTO3
  when: ansible_os_family == "Debian"
  pip:
    name:
      - boto3
      - boto
    state: present

- name: Installing AWS module dependency BOTO and BOTO3
  when: ansible_os_family == "RedHat"
  pip:
    name:
      - boto3
        #      - boto
    state: present

- name: Installing Required Utils for provisioning
  apt: 
    name:
      - curl
      - wget
      - unzip
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Installing Required Utils for provisioning
  yum: 
    name: 
      - curl
      - wget
      - unzip
    state: present
  when: ansible_os_family == "RedHat"
