---
- include_tasks: docker.yml
  when: container_runtime == "docker"

- include_tasks: containerd.yml
  when: container_runtime == "containerd"

- include_tasks: crio.yml
  when: container_runtime == "crio"
