---

- name: Updating python
  apt:
    name: python
    state: present
    update_cache: yes
  when: 
    - "'3' not in ansible_facts.python_version"
    - when: ansible_os_family == "Debian"

- name: Updating python
  yum:
    name: python
    state: present
  when: 
    - "'3' not in ansible_facts.python_version"
    - when: ansible_os_family == "RedHat"

- name: Installing boto3 library"
  when: ansible_os_family == "Debian"
  pip:
    name: boto3
    state: present

- name: Installing boto3 library"
  when: ansible_os_family == "RedHat"
  pip:
    name: boto3
    state: present
