---
- name: Launching Master Node
  ec2:
    key_name: "{{ key_name.key.name }}"
    instance_type: t2.micro
    image: ami-08962a4068733a2b6
    wait: true
    group: "{{ sg_id.group_name }}"
    count: 1
    vpc_subnet_id: "{{ vpc_subid }}"
    assign_public_ip: yes
    region: us-east-2
    user_data: |
               #!/bin/bash
               apt update -y
               apt install curl python-y
               curl https://raw.githubusercontent.com/khann-adill/play-with-kubectl/master/kubernetes-installation/set-hostname-kmaster.sh | bash
    state: present
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    instance_tags:
          Name: MasterNode
  register: master_info

- name: "Setting MasterNode Public IP as variable"
  set_fact:
      master_ip: "{{ item.public_ip }}"
  loop: "{{ master_info['instances'] }}"
  
- name: Getting Inventory file.
  template:
     src: ../templates/custom_inv.j2
     dest: /etc/ansible/custom_inv.ini 

- name: Adding MasterNode to inventory file.
  lineinfile:
        line: "{{ item.public_ip }}"
        dest: /etc/ansible/custom_inv.ini
        insertafter: '\[master\]'
  loop: "{{ master_info['instances'] }}"
  register: line


