---
- name: Launching Worker Node
  ec2:
    key_name: "{{ key_name.key.name }}"
    instance_type: t2.micro
    image: "{{ ec2.vm_image }}"
    wait: true
    group: "{{ sg_id.group_name }}"
    count: 2
    vpc_subnet_id: "{{ vpc_subid }}"
    assign_public_ip: yes
    region: us-east-2
    user_data: |
               #!/bin/bash
               apt update -y
               apt install curl -y
               curl https://raw.githubusercontent.com/khann-adill/play-with-kubectl/master/kubernetes-installation/set-hostname-kworker.sh | bash
    state: present
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    volumes:
        - device_name: "{{ ec2.master.volume.volume_device_name }}"
          volume_type: "{{ ec2.master.volume.volume_type }}"
          volume_size: "{{ ec2.master.volume.volume_size }}"
          delete_on_termination: "{{ ec2.master.volume.volume_termination }}"
    instance_tags:
          Name: WorkerNode
  register: worker_info

- name: "Setting  WorkerNodes Public IP as variable"
  set_fact:
      worker_ip: "{{ item.public_ip }}"
  loop: "{{ worker_info['instances'] }}"

- name: Adding WorkerNode to Inventory file
  lineinfile:
        line: "{{ item.public_ip }} "
        dest: /etc/ansible/custom_inv.ini
        insertafter: '\[worker\]'
  loop: "{{ worker_info['instances'] }}"
