---
- include_vars: ../vars/cred.yml
- include: required-packages.yml
- include: security_group.yml
- include: ssh_key.yml 
- include: aws_key_creation.yml
- include: getting_vpc_subnetid.yml
- include: ec2-master.yml
- include: ec2-worker.yml
- include: ssh-check.yml 
- include: refresh_inventory.yml
