---
- name: "Security Group for both Master and Worker Nodes"
  ec2_group:
     name: "{{ ec2.security_group.group_name }}"
     description: "This SG allows allows all traffic"
     region: "{{ ec2.region }}"
     aws_access_key: "{{ access_key }}"
     aws_secret_key: "{{ secret_key }}"
     rules:
     - proto: all
       cidr_ip: 0.0.0.0/0
     rules_egress:
     - proto: all
       cidr_ip: 0.0.0.0/0
  register: sgroup_name
