---
- name: "Create checkout directory"
  file:
    path: "{{ kube_addon_dir }}"
    state: directory
    mode: 0755

- block:
    - name: "Check if Helm is installed"
      shell: command -v helm >/dev/null 2>&1
      register: helm_exists
       #  ignore_errors: yes
  rescue:
    - name: Install Helm | Get Helm installer
      get_url:
        url: "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3"
        dest: "{{ kube_addon_dir }}/get_helm.sh"
        mode: 0755
      when: helm_exists.rc > 0

    - name: "Run the installer"
      shell: "{{ kube_addon_dir }}/get_helm.sh"
      when: helm_exists.rc > 0

- name: "Adding Helm Stable REPO"
  shell: "helm repo add stable https://charts.helm.sh/stable"

  
