---
- name: Generating inventory file
  block:
   - name: Copying Inventory template
     template:
         src: custom_inv.j2
         dest: /etc/ansible/custom_inv.ini 
   - name: Adding MasterNode to inventory file
     lineinfile:
        line: "{{ item.public_ip_address }}"
        dest: /tmp/ip.txt
        insertafter: '\[worker\]'
     loop: "{{ ec2['instances'] }}"
     register: line

     
  always:
   - debug: 
       msg: "Custom Inventory file has been succesfully created, :-)"
