---
- name: Generating inventory file
  block:
    - name: Downloading inventory generator script
      get_url:
           url: https://raw.githubusercontent.com/khann-adill/kubernetes-ansible/main/ansible_inv_generator/inv.sh
           dest: /tmp/
           mode: 0755
    - name: Generating inventory file
      shell: "sh /tmp/inv.sh {{ item.master.public_ip }} {{ item.worker.public_ip }}"
      loop:
        - { master: "{{ master_info['instances'] }}" }
        - { worker: "{{ worker_info['instances'] }}" }
