---
- name: Install apt-transport-https (Debian/Ubuntu)
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
    
- name: Configure module for containerd
  copy:
   src: containerd.conf
   dest: /etc/modules-load.d/containerd.conf
   mode: 0644

- name: Configure sysctl params for Kubernetes
  copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    mode: 0644

- name: Apply sysctl params without reboot
  command: sysctl --system

- name: Adding Docker APT GPG key (Debian/Ubuntu)
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  when: ansible_os_family == "Debian"

- name: Add docker APT repository (Debian/Ubuntu)
  apt_repository:
         repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
         state: present
         filename: 'docker'
  when: ansible_os_family == "Debian"

- name: Install containerd
  apt:
   name: containerd.io
   state: present

- name: Configure containerd
  file:
    path: /etc/containerd
    state: directory

- name: Configure containerd
  shell: /usr/bin/containerd config default > /etc/containerd/config.toml

- name: Enable containerd service, and start it
  systemd:
     name: containerd
     state: restarted
     daemon-reload: yes
     enabled: yes
