---
- name: Adding Kubernetes APT GPG key (Debian/Ubuntu)
  apt_key:
     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
     state: present
  when: ansible_os_family == "Debian"

- name: Add Kubernetes APT repository (Debian/Ubuntu)
  apt_repository:
       repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
       state: present
       filename: 'kubernetes'
  when: ansible_os_family == "Debian"

- name: Install kubernetes packages (Debian/Ubuntu)
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  with_items: "{{ packages }}"
  when: ansible_os_family == "Debian"

- name: Disable system swap
  shell: "swapoff -a"
  
- name: Remove swap entry from /etc/fstab
  lineinfile:
     dest: /etc/fstab
     regexp: swap
     state: absent
