name: Ansible Lint
on:
 push:
   branches:
        - main
        - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Set up Python 3.6
       uses: actions/setup-python@v1
       with:
         python-version: 3.6
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install ansible-lint
     - name: Lint playbook
       run: ansible-lint -t deprecations roles/*
