name: Ansible yamllint
on: [push, pull_request]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint validation for k8s roles
      uses: ibiqlik/action-yamllint@v3
      with:
        config_file: .yamllint
