name: Ansible Lint
on:
 push:
   branches:
        - main
        - development
 schedule:
    - cron: "0 11 * * 1-5"
jobs:
  test:
    name: Ansible role Testing
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Set up Python 3.6
       uses: actions/setup-python@v1
       with:
         python-version: 3.6
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install ansible ansible-lint
     - name: Checking deprecations in playbook
       run: ansible-lint -t deprecations roles/*
     - name: Checking formatting in Playbooks
       run: ansible-lint -t formatting roles/*
     - name: Checking Core test of lint in Playbooks
       run: ansible-lint -t core roles/*
